### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by kotoku-code**
## Design Tear-down: Smashing Magazine clone
- Used css grid
- colored the sections different variants of grey

[Live Version] https://raw.githack.com/Krishnabot/Design-Teardown/feature-branch/index.html

Please feel free to comment or ask us any questions.

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
## Hi @kotoku-code @Krishnabot,
Your project looks good, great job guys 👏👏. However, there are a few things that you need to fix.
**README**
- The link in your README is broken, please add one that works.
- The one on your Pull Request Description is also broken.

**Navigation bar**
- It uses `div` and positions elements as at the source page, make sure you use `div` just like how it is used on the original page.

**3 articles rows**
- It contains 3 articles, **each takes one-third of the width**, your 3 articles in a row don't take a third of the width.

**Each article**
- Make sure all your articles use `<article>` tag ( this includes the articles which are 1 or 2 or 3 in a row), see a screenshot of [requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/article_requirement.png).

**Footer**
- You currently don't have a footer or it's blank, your footer should contain centered links.

**[OPTIONAL]**
- When you add a footer, I suggest you use the `<footer>` tags.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes then request for another code review.
### Status: Changes Required 🛑
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

**Comment by kotoku-code** [comment]
Thank you for the feed back.
-we have added article elements
-added divs to the nav section
-created a footer section with centered links

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in 15 minutes for some feedback :handshake:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello @kotoku-code!
I see you made a change mid-review, this is the change I was going to propose :laughing: That being said, please request another review so we can get this approved! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — APPROVED** [review]
# Congrats @kotoku-code and @Krishnabot 
You have done a really great job on this one! :rocket: Please merge this and keep moving forward :handshake: See you at the top :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
